# Generated by Django 2.1.5 on 2019-03-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='Image',
        ),
    ]
